### ISSUE TITLE
Create github pages for this repository

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/Ultimate-DevOps-Resources#20]

**Comment by Adidem23** [comment]
Thank You

**Comment by ayushsgithub** [comment]
Hey @Adidem23 mate, are you still working on this issue?
@DhanushNehru If it's still open and not resolved yet, I would love to work on this issue and I request you to please assign it to me

**Comment by Adidem23** [comment]
Yeah , No problem mate @ayushsgithub  You can take this issue . bhaiya @DhanushNehru  You can assign this issue to @ayushsgithub
